---
title: 'Exercise 4_1_2: Regression analysis'
author: 'Johannes Breuer, Stefan Jünger, Veronika Batzdorfer'
date: 'Introduction to R for Data Analysis'
editor_options: 
  chunk_output_type: console
---

```{r child = "./content/config/exercises_setup.Rmd"}
```

As per usual, we first need to load our data. This time, we also wrangle some variables at the beginning. So please execute the following R commands.

```{r load}
library(dplyr)
library(haven)

allbus_2021_cda_2 <- 
  read_spss("./data/allbus_2021/ZA5280_v1-0-0.sav") %>% 
  mutate(
    trust_parliament = as.numeric(pt03),
    party = pv01,
    political_orientation = as.numeric(pa01),
    satisfaction_democracy = ifelse(as.numeric(ps03) <= 2, 1, 0)
  )
```

In case you have not done so yet, please also install the `performance` package for this set of exercises.

```{r pkgs, eval = F}
if (!require(performance)) install.packages("performance")
```

In the following exercise, we will cover/repeat some of the basics of regression analysis in `R`.

```{block, box.title = "1", box.body = list(fill = "white"), box.icon = "fa-star"}
To begin with, run a simple linear regression model with trust in the German federal parliament (`trust_parliament`) as the outcome variable and choice of party (`party`) and political orientation (`political_orientation`) as predictors.
```

```{block, opts.label = "clues"}
To get some (more) informative output, you can use `summary()` again. 
```

```{r first-exercise, solution = TRUE}
reg_linear <- 
  lm(trust_parliament ~ party + political_orientation, data = allbus_2021_cda_2)

summary(reg_linear)
```

```{block, box.title = "2", box.body = list(fill = "white"), box.icon = "fa-star"}
As the next step in our analyses, we want assess whether these whole previous findings have something to do with satisfaction in democracy. For this purpose, we switch the dependent variable to satisfaction with democracy and move the the trust in parliament variable to the independent ones. **Attention**: We now have to run a logistic regression.
```

```{block, opts.label = "clues"}
This time, you need the `glm()` function in which you need to specify a link function. The name of the outcome variable is `satisfaction_democracy`.
```

```{r second-exercise, solution = TRUE}
reg_logistic <- 
  glm(
    satisfaction_democracy ~ trust_parliament + party + political_orientation,
    family = binomial(link = "logit"),
    data = allbus_2021_cda_2
  )

summary(reg_logistic)
```

```{block, box.title = "3", box.body = list(fill = "white"), box.icon = "fa-star"}
Reviewer 2 is at it again... As Cauchit links are all the rage in her/his field, she/he wants us to run the same model with the sole difference of using a cauchit link.... sigh!
```

```{block, opts.label = "clues"}
Have a look at the help page `?family` to see how you can include a cauchit link.
```

```{r third-exercise, solution = TRUE}
reg_cauchit <- 
   glm(
    satisfaction_democracy ~ trust_parliament + party + political_orientation,
    family = binomial(link = "cauchit"),
    data = allbus_2021_cda_2
  )

summary(reg_cauchit)
```

```{block, box.title = "4", box.body = list(fill = "white"), box.icon = "fa-star"}
Compare both regression models using an ANOVA. Use the argument `test = "LRT"` in the function we need for this to perform a likelihood ratio test. What's your interpretation?
```

```{block, opts.label = "clues"}
A p-value considered as statistically significant would indicate a difference between the models.
```

```{r fourth-exercise, solution = TRUE}
anova(reg_logistic, reg_cauchit, test = "LRT")

# Interpretation of difference:
# It seems there is no big difference. We can make the reviewer happy with the
# cauchit models and still keep our main findings.
```

```{block, box.title = "5", box.body = list(fill = "white"), box.icon = "fa-star"}
To be extra sure that there is no meaningful difference between the logit and the cauchit model, let's also compare some fit parameters. We want the following model fit metrics: AIC, BIC, R², and RMSE
```

```{block, opts.label = "clues"}
The `performance` package provides a function for comparing the performance of different models in terms of their fit.
```

```{r fifth-exercise, solution = TRUE}
compare_performance(
  reg_logistic,
  reg_cauchit,
  metrics = c("AIC", "BIC", "R2", "RMSE")
)
```
