---
title: 'Exercise 3_2_3: Plotting Repeats'
author: 'Johannes Breuer, Stefan Jünger, Veronika Batzdorfer'
date: 'Introduction to R for Data Analysis'
---

```{r child = "./content/config/exercises_setup.Rmd"}
```

~~History~~ Plotting repeats. Let's dive into `ggplot2` and repeat what we've done in `base R` using the "grammar of graphics".

Here's the Allbus 2021 data again.

```{r loadallbus2021, message=FALSE, eval=TRUE}
library(dplyr)
library(haven)

allbus_2021_dvI <- 
  read_sav(
    "./data/allbus_2021ZA5280_v1-0-0.sav"
  ) %>% 
  sjlabelled::set_na(na = c(-1:-99, 97, 98))
```

```{block, box.title = "1", box.body = list(fill = "white"), box.icon = "fa-star"}
Create a scatter plot for the variables `pa01` (political_orientation) and `fr03b` (children suffer under working mothers).
```

```{block, opts.label = "clues"}
Remember the order of layers: `data + aesthetics + geoms`
```

```{r scatter, solution = TRUE}
library(ggplot2)

ggplot(
  allbus_2021_dvI,
  aes(pa01, fr03b)
) +
  geom_point()
```

```{block, box.title = "2", box.body = list(fill = "white"), box.icon = "fa-star"}
Add some jitter to the scatter plot.
```

```{block, opts.label = "clues"}
In contrast to the `base R` function jitter does not have to be added; it just replaces the original `geom` using `geom_jitter()`
```

```{r jitter, solution = TRUE}
ggplot(
  allbus_2021_dvI,
  aes(pa01, fr03b)
) +
  geom_jitter()
```

```{block, box.title = "3", box.body = list(fill = "white"), box.icon = "fa-star"}
Boxplots are boring, right? Try to plot the relationship between `pa01` (political_orientation) and `fr03b` (children suffer under working mothers) as a violin plot! Have a look here for reference: https://ggplot2.tidyverse.org/reference/

What's the difference to a boxplot?
```

```{block, opts.label = "clues"}
You can't find the proper `geom`? Try `geom_violin()`.
```

```{r violin, solution = TRUE}
ggplot(
 allbus_2021_dvI,
  aes(pa01, fr03b)
) +
  geom_violin()

# In contrast to simple boxplots, violin plots show densities and can, e.g.,
# help to assess whether a variable is normally distributed or not.
```
