---
title: 'Exercise 2_1_2: Filtering & arranging rows'
author: 'Johannes Breuer, Stefan Jünger, & Veronika Batzdorfer'
date: 'Introduction to R for Data Analysis'
---

```{r child = "../config/exercises_setup.Rmd"}
```

In this set of exercises, we will practice filtering and rearranging the order of rows.

As for the previous set of data wrangling exercises, before we can begin, we need to load the `tidyverse` package(s) and import the data. Also for these exercises, it is advisable to open the *AKTUELLER LINK* [codebook for the data set](https://dbk.gesis.org/dbksearch/download.asp?id=67378).

```{r read-data, message = F}
library(tidyverse)
library(haven)


allbus_2021 <- read_sav("./data/allbus_2021ZA5280_v1-0-0.sav")
```

```{block, box.title = "1", box.body = list(fill = "white"), box.icon = "fa-star"}
As a first exercise, using `base R`, let's create a new data set named `allbus_single` that only contains data from respondents who reported being single.
```

```{block, opts.label = "clues"}
The variable representing marital status is named `mstat` and the value indicating that the respondent is married is 5. Remember that there are 2 options in `base R` for filtering rows (the same ones as for selecting columns).
```

```{r first-exercise, solution = TRUE}
# Option 1
allbus_single <- allbus_2021[allbus_2021$mstat == 5, ]

# Option 2
allbus_single <- subset(allbus_2021, mstat == 5)
```

```{block, box.title = "2", box.body = list(fill = "white"), box.icon = "fa-star"}
Now, let's use the `dplyr` function for filtering rows: Create an object named `allbus_male_sober_driver` that only contains respondents who report that they are male as well as never having driven a car whilst being drunk in the past.
```

```{block, opts.label = "clues"}
The names of the variables we need here are `sex` and `cs02` (drunk driving) and the values we want to filter for are 1 (male), and 1 (never), respectively.
```

```{r second-exercise, solution = TRUE}
allbus_male_sober_driver <- allbus_2021 %>% 
  filter(sex == 1,
         cs02 == 1)
```

```{block, box.title = "3", box.body = list(fill = "white"), box.icon = "fa-star"}
Using the same function from `dplyr`, create another subset of cases called `allbus_social_media_news` that only includes respondents that stated that they use social media between (inclusively) *three to five* days per week as a means of news source.
```

```{block, opts.label = "clues"}
The variable we need for this is called `lm35` and the values of that variable we are looking for are 3 to 5. You can use the helper function `between()` here (remember that the values you provide to this function are inclusive).
```

```{r third-exercise, solution = TRUE}
allbus_social_media_news <- allbus_2021 %>% 
  filter(between(lm35, 3, 5))
```

```{block, box.title = "4", box.body = list(fill = "white"), box.icon = "fa-star"}
Let's briefly turn back to `base R` for this task: Sort the `allbus_2021` data set in descending order of the `ls01` (general life satisfaction) variable. You can overwrite the original `allbus_2021` object for this task. Have a look at the resulting data frame to check if your code worked.
```

```{block, opts.label = "clues"}
You need the `base R` function `order()` here. You can check your result using `head()`. To limit the amount of output, you can subset columns using [ ] within the `head()` command (general life satisfaction is the *513th* variable in the data set, so you could, e.g., subset columns 510:*513*).
```

```{r fourth-exercise, solution = TRUE}
allbus_2021 <- allbus_2021[order(desc(allbus_2021$ls01)),]

head(allbus_2021[, 510:513])
```

```{block, box.title = "5", box.body = list(fill = "white"), box.icon = "fa-star"}
Let's rearrange the order of rows again, this time using a function from the `dplyr` package. To restore the original order of the `allbus_2021` data set, sort in ascending order of the `respid` variable. As for the previous task, check whether your code works, but this time using a (short) pipe chain and a `dplyr` function for catching a glimpse of your data.
```

```{block, opts.label = "clues"}
The `dplyr` function you are looking for is in another castle... Just kidding (and apologies for the silly "Super Mario" reference here... that's what happens when you work with pipes more than a plumber does), it's `arrange()`.  
```

```{r fifth-exercise, solution = TRUE}
albus_2021 <- allbus_2021 %>% 
  arrange(respid)

allbus_2021 %>% 
  select(respid:ls01) %>% 
  glimpse()
```